"""initial schema

Revision ID: 419e0e23fe81
Revises: 
Create Date: 2026-08-14 09:16:25.358713

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '419e0e23fe81'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('chesscom_username', sa.String(), nullable=True),
    sa.Column('pgn_file_path', sa.String(), nullable=True),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('white_player', sa.String(), nullable=False),
    sa.Column('black_player', sa.String(), nullable=False),
    sa.Column('result', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('eco_code', sa.String(), nullable=True),
    sa.Column('pgn_data', sa.Text(), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('imported_games', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_imported_games_eco_code'), ['eco_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_imported_games_game_id'), ['game_id'], unique=False)

    op.create_table('repertoires',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('game_variants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('moves', sa.Text(), nullable=False),
    sa.Column('starting_position', sa.String(), nullable=False),
    sa.Column('evaluation', sa.Float(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['imported_games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('game_variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_game_variants_game_id'), ['game_id'], unique=False)

    op.create_table('repertoire_lines',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repertoire_id', sa.String(), nullable=False),
    sa.Column('variant_id', sa.String(), nullable=True),
    sa.Column('moves', sa.Text(), nullable=False),
    sa.Column('starting_position', sa.String(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('last_reviewed', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['game_variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('repertoire_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_repertoire_lines_repertoire_id'), ['repertoire_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_repertoire_lines_variant_id'), ['variant_id'], unique=False)

    op.create_table('memorization_stats',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('success_rate', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['repertoire_lines.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memorization_stats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memorization_stats_line_id'), ['line_id'], unique=False)

    op.create_table('training_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('repertoire_id', sa.String(), nullable=False),
    sa.Column('line_id', sa.String(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('date', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_answers', sa.Integer(), nullable=False),
    sa.Column('time_spent', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['line_id'], ['repertoire_lines.id'], ),
    sa.ForeignKeyConstraint(['repertoire_id'], ['repertoires.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_training_sessions_line_id'), ['line_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_training_sessions_repertoire_id'), ['repertoire_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('training_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_training_sessions_repertoire_id'))
        batch_op.drop_index(batch_op.f('ix_training_sessions_line_id'))

    op.drop_table('training_sessions')
    with op.batch_alter_table('memorization_stats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memorization_stats_line_id'))

    op.drop_table('memorization_stats')
    with op.batch_alter_table('repertoire_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_repertoire_lines_variant_id'))
        batch_op.drop_index(batch_op.f('ix_repertoire_lines_repertoire_id'))

    op.drop_table('repertoire_lines')
    with op.batch_alter_table('game_variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_game_variants_game_id'))

    op.drop_table('game_variants')
    op.drop_table('repertoires')
    with op.batch_alter_table('imported_games', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_imported_games_game_id'))
        batch_op.drop_index(batch_op.f('ix_imported_games_eco_code'))

    op.drop_table('imported_games')
    # ### end Alembic commands ###
